name: fedxgboost_mpi
channels:
  - defaults
dependencies:
  - python=3.8
  - packaging=21.3
  - fonttools
  - numpy
  - kiwisolver=1.4.2
  - pandas=1.4.2
  - matplotlib=3.5.1
  - pytz=2022.1
  - mpi4py
  - six=1.16.0
  - pillow
  - python-dateutil=2.8.2
  - scipy
  - xgboost
  - cycler=0.11.0
  - pyparsing
  - ca-certificates
  - certifi
  - openssl
  - openmpi
  - gxx_linux-64
  - gcc
  - graphviz
  - imbalanced-learn
# prefix: /home/meerhofj/.conda/envs/fedxgboost_mpi
